services:
  marketplace-server:
    volumes:
      - .:/usr/src/app:cached
      - marketplace-server-node_modules:/usr/src/app/node_modules
      - ${HOME}/.ssh:/home/node/.ssh:ro
      - ${HOME}/.gitconfig:/home/node/.gitconfig:ro

  redis:
    ports:
      - "6379:6379"

volumes:
  marketplace-server-node_modules:
